### ISSUE TITLE
Change button style 

### ISSUE THREAD

**Issue by MeijeSibbel** [lakewik/storj-gui-client#47]
currently the `upload` icon is a small orange (+) icon and the `remove` icon a large red icon. It should be vice-versa. The upload button should be a green icon just like download with the `upload` text. Then the delete icon can be the same form factor and at location as the (+) icon is currently, but then switch the (+) for a (x). I would also make the `mirrors` icon smaller as it is less important than the `upload` and `download` buttons.

**Comment by lakewik** [comment]
![zaznaczenie_144](https://cloud.githubusercontent.com/assets/9087566/25562945/fe27641e-2d91-11e7-8f49-6f84b7a3b457.png)
@MeijeSibbel It is ok?

**Comment by MeijeSibbel** [comment]
@lakewik , perfect!

**Comment by lakewik** [comment]
Done in branch develop.
