### ISSUE TITLE
Wrong encoding for download file

### ISSUE THREAD

**Issue by AlexeyALeonov** [lakewik/storj-gui-client#48]
I'm trying to download a file with non-ASCII characters in the name. I got this:
![default](https://cloud.githubusercontent.com/assets/26858949/25559378/549c8e92-2d41-11e7-922d-b2895687ed77.png)

**Comment by lakewik** [comment]
Done in branch develop

**Comment by AlexeyALeonov** [comment]
![default](https://cloud.githubusercontent.com/assets/26858949/25567457/bba0e6aa-2df6-11e7-99f8-b7572583111c.png)

**Comment by AlexeyALeonov** [comment]
It was for v2
