### ISSUE TITLE
Feature: Automatically scroll down as the shards download/upload to keep-up with the process. 

### ISSUE THREAD

**Issue by MeijeSibbel** [lakewik/storj-gui-client#51]
Right now if you start a download/download it starts downloading shard 1-x, after shard 7 the new shards that are downloaded/uploaded are our of the viewing area. By automatically scrolling down to always have the latest active shard in the viewing area helps the user to track the entire upload process without having scroll down every time to see the latest active shard.

**Comment by lakewik** [comment]
Done in branch develop
