### ISSUE TITLE
Feature: Allow sorting of file list

### ISSUE THREAD

**Issue by MeijeSibbel** [lakewik/storj-gui-client#54]
E.g.

- One clicks on 'File Name' category -> a arrow goes down -> sorts by alphabetical order. Arrow up -> vice-versa
- One clicks on 'File Size' category -> sorts from smallest to largest size. Arrow up -> vice-versa.
(...)

This works like normal file sorting in a directory.

This allows the user to sort the list of files based on their preference.

**Comment by lakewik** [comment]
Sorting by file name done
