### ISSUE TITLE
OSx build

### ISSUE THREAD

**Issue by rizhenkov** [lakewik/storj-gui-client#86]
Hello. As I understand, that project is multiplatform. 
Is it possible to release Mac OS version too?

**Comment by lakewik** [comment]
Hi @riartem Yes, I get it working (upload and download working) on Mac OS X when running from source but currently pyinstaller (software to create binary package from source files) have problems with building binary package. I will try to package it for Mac when it out Alpha

**Comment by rizhenkov** [comment]
👍  Thank you for quick response.
I'll look forward to the release beta :)
