### ISSUE TITLE
Register new user fails

### ISSUE THREAD

**Issue by schwab** [lakewik/storj-gui-client#99]
Enter fields in new user registration. Bridge URL is missing??? Entered api.storj.io in bridge url.  

Traceback error in initial terminal:
Traceback (most recent call last):
  File "/home/mcstar/Downloads/storj-gui-client/UI/registration.py", line 43, in register
    self.storj_client = storj.Client(None, "", api_url=self.bridge_api_url).user_create(str(self.email).strip(), str(self.password).strip())
TypeError: __init__() got an unexpected keyword argument 'api_url'

**Comment by marcorosa** [comment]
Solved by PR #102
